### ISSUE TITLE
[rush] 401 errors when calling install-run-rush.js from Azure Devops pipeline with private npm feed

### ISSUE THREAD

**Issue by bvancea** [microsoft/web-build-tools#1278]
My team is running into some issues trying to set up rushjs on a monorepo for Microsoft Dynamics 365 Market Insights.
We are trying to set up an Azure Devops build pipeline for our project, more details below.

1. We use a custom Azure Devops artiface feed, and specify the registry url and credentials in `common/config/rush/.npmrc`:

    ```
    registry=<private-feed-url>
    always-auth=true
    ```

1. We use the `npmAuthenticate@0` task to add the npm credentials to this `.npmrc` file.

    ```yaml
    - task: npmAuthenticate@0
        displayName: 'Configuring private feeds via .npmrc & configuring authentication'
        inputs:
            workingFile: 'common/config/rush/.npmrc'
            customEndpoint: <Feed Name>
    ```

1. We try to bootstrap Rush using the `install-run-rush.js` script. We have the following steps defined in our pipeline defintion:

    ```yaml
    - script: 'node common/scripts/install-run-rush.js change --verify'
        displayName: 'Verify Change Logs'
    - script: 'node common/scripts/install-run-rush.js install'
        displayName: 'Rush Install'
    - script: 'node common/scripts/install-run-rush.js build'
        displayName: 'Building'
    /// other tasks below
    ```

When running the pipeline, we get the following error:

```bash
The rush.json configuration requests Rush version 5.7.3
Installing @microsoft/rush...
npm info it worked if it ends with ok
npm verb cli [ '/workspace/_tool/node/10.15.3/x64/bin/node',
npm verb cli   '/workspace/_tool/node/10.15.3/x64/bin/npm',
npm verb cli   'install' ]
npm info using npm@6.4.1
npm info using node@v10.15.3
npm verb npm-session 39e5528a7d2d7a76
npm info lifecycle ci-rush@0.0.0~preinstall: ci-rush@0.0.0
npm timing stage:loadCurrentTree Completed in 11ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
npm http fetch GET 401 <private-feed-url>/@microsoft%2frush 181ms
npm http fetch GET 401 <private-feed-url>/@microsoft%2frush 98ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 471ms
npm verb stack Error: 401 Unauthorized: @microsoft/rush@5.7.3
npm verb stack     at fetch.then.res (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/workspace/_tool/node/10.15.3/x64/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:705:18)
npm verb stack     at tryOnImmediate (timers.js:676:5)
npm verb stack     at processImmediate (timers.js:658:5)
npm verb cwd /workspace/60/s/common/temp/install-run/@microsoft+rush@5.7.3
npm verb Linux 4.15.0-1037-azure
npm verb argv "/workspace/_tool/node/10.15.3/x64/bin/node" "/workspace/_tool/node/10.15.3/x64/bin/npm" "install"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code E401
npm ERR! 401 Unauthorized: @microsoft/rush@5.7.3
npm verb exit [ 1, true ]
npm timing npm Completed in 862ms
```

Any ideas on what we are doing wrong here? It looks like rush picks up the repository url, but does not see the credentials.

We also tried:

- putting the credentials on an `.npmrc` in the home directory,
- installing rushjs via npm, although this creates issues with phantom dependencies.

**Comment by octogonz** [comment]
@iclanton has set up many internal repos at Microsoft

**Comment by octogonz** [comment]
BTW I recommend against using the `npmAuthenticate` task because it writes your credentials to a file on disk, which is a security concern. For example, if the machine loses power before the file is deleted, the file will be preserved indefinitely and contains credentials in plain text. We recommend to authenticate using an environment variable instead. Ian can refer you to other repo configurations that you can use as an example.

**Comment by iclanton** [comment]
Here's what we do for Azure DevOps pipelines, talking to a private package feed:

1. In `common/config/rush/.npmrc`, also include a macro for the auth token. Your `.npmrc` should look like this:

```
# Rush uses this file to configure the package registry, regardless of whether the
# package manager is PNPM, NPM, or Yarn.  Prior to invoking the package manager,
# Rush will always copy this file to the folder where installation is performed.
# When NPM is the package manager, Rush works around NPM's processing of
# undefined environment variables by deleting any lines that reference undefined
# environment variables.
#
# DO NOT SPECIFY AUTHENTICATION CREDENTIALS IN THIS FILE.  It should only be used
# to configure registry sources.

registry=<private-feed-url>/registry
<private-feed-url>/registry/:always-auth=true
<private-feed-url>/registry/:_authToken=${PACKAGE_FEED_AUTH_TOKEN}
<private-feed-url>/:_authToken=${PACKAGE_FEED_AUTH_TOKEN}
```

2. Like @octogonz said, we strongly recommend **against** using the `npmAuthenticate` pipeline task. Instead, set the `persistCredentials` option in your `checkout` step to `true`. You likely don't already have a `checkout` step in your pipeline because the default value of `- checkout: self` is implied if the step isn't explicitly specified. Add the `checkout` step as the first step in your pipeline like this:

```YAML
steps:
- checkout: self
  persistCredentials: true
```

3. In any script steps where rush needs to install things (like `rush install` steps, or the first time you run `install-run-rush` when rush needs to install itself), include an `env` variable populating the name you picked in your `.npmrc` with the access token. For example:

```YAML
- script: 'node common/scripts/install-run-rush.js change --verify'
  displayName: 'Verify Change Logs'
  env:
    PACKAGE_FEED_AUTH_TOKEN: $(System.AccessToken)
- script: 'node common/scripts/install-run-rush.js install'
  displayName: 'Rush Install'
  env:
    PACKAGE_FEED_AUTH_TOKEN: $(System.AccessToken)
```

So, putting it all together, your pipeline YAML will look something like this:

```YAML
steps:
- checkout: self
  persistCredentials: true

- script: 'node common/scripts/install-run-rush.js change --verify'
  displayName: 'Verify Change Logs'
  env:
    PACKAGE_FEED_AUTH_TOKEN: $(System.AccessToken)

- script: 'node common/scripts/install-run-rush.js install'
  displayName: 'Rush Install'
  env:
    PACKAGE_FEED_AUTH_TOKEN: $(System.AccessToken)

- script: 'node common/scripts/install-run-rush.js build'
  displayName: 'Building'
```
