### ISSUE TITLE
pnpm is not private npm-friendly

### ISSUE THREAD

**Issue by Jabher** [microsoft/web-build-tools#1500]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
While using PNPM (neither yarn nor npm produces this error) with our company private registry I'm always encountering the following kind of error:
```
ERROR: Cannot parse pnpm shrinkwrap version specifier:
"%PRIVATE_REGISTRY_URL%/eslint-config-airbnb-base/14.0.0_00f6cc13a807540353016e46f0b7d569" for "eslint-config-airbnb-base"
```

E.g.
part of project is common eslint config.
It is represented in pnpm-lock.yaml in following parts:
```
'file:projects/eslint-config.tgz':
    dependencies:
      eslint: %PRIVATE_REGISTRY_URL%/eslint/5.16.0
      eslint-config-airbnb-base: %PRIVATE_REGISTRY_URL%/eslint-config-airbnb-base/14.0.0_00f6cc13a807540353016e46f0b7d569
```

As far as I understand this is related to some rush-specific behavior of pnpm (as pnpm solely does not produce this kind of error).
Is it possible to provide some kind of flag for `rush.json` to disable this error?

* **Tool: Rush** 
* **Tool Version: 5.11.4** 
* **Node Version: 10.x.x** 
  * **Is this a LTS version? yes** 
  * **Have you tested on a LTS version? yes** 
* **OS: Mac OS**
